### ISSUE TITLE
Check that SharePoint files can be made publicly available

### ISSUE THREAD

**Issue by hannahkates** [NYCPlanning/labs-applicant-portal#10]
Make sure that sharepoint links can be accessible by any member of the public so that documents can be posted on the project's page.

Right now, it's not possible to make the sharepoint URLs viewable to the public, but we need to be able to share files that are stored on sharepoint with the public through the project profiles on zap search. We need to figure out if they have been made available through our API if our API is an approved sharepoint user.

In sharepoint itself, it isn't possible to change the settings on the files to be public. We need to figure out how to make the files available to the public through our API's access to them.

**Comment by allthesignals** [comment]
I'm not sure I understand this but I'm seeing some URLs in the API that point to this: 

https://nyco365.sharepoint.com/sites/dcppfsuat2/dcp_package/2018K0354 - Draft LU Application - 1_ED01F3BF4C20EA11A9AC001DD8308025

They seem to work...

**Comment by allthesignals** [comment]
I'll need to understand more what the issue here is, where the concern's coming from...

**Comment by allthesignals** [comment]
@CeciliaCY hiiiiii — can we pick your brain on this sometime this week? :)

**Comment by trbmcginnis** [comment]
I'm assuming we just update the permissions on the Artifacts folder to `public`? 

https://nyco365.sharepoint.com/sites/dcppfsuat2/dcp_artifacts/Forms/AllItems.aspx?viewid=9d0a3705%2Dea3a%2D4e45%2D8131%2D78ec7dfb4dc8

**Comment by trbmcginnis** [comment]
Going to try to get this working in Postman

https://medium.com/@anoopt/accessing-sharepoint-data-using-postman-sharepoint-rest-api-76b70630bcbf

**Comment by godfreyyeung** [comment]
# Retrieving a document investigation:

## Can it be done through the CRM API?
 
DownloadFile endpoint failed

## Can we make a request directly to Sharepoint?

### Sharepoint REST API v1

The Sharepoint Rest API provides an interface to get and retrieve items:
 
An example URL that will directly download a file is:

**Comment by godfreyyeung** [comment]
Had a great meeting with Chengying, Ella and Heidi. Learned some great news! 

- Ella has ran through creating certs for LikeMinded's connection the CRM Portal deployments. She can look for the cert creation instructions for us, so that I can compare how LikeMinded did it vs. how we recently created certs.

- Chengying now has access to the appregnew.aspx page. We can potentially use this avenue to register applications that allow us to access sharepoint, now.

- Chengying has experience writing .NET to connect to sharepoint for file upload. She can share her code that can potentially be good examples of how to connect to sharepoint for file retrieval.
