### ISSUE TITLE
The uploaded document is not displayed as hyperlink and added document does not move to be added uploaded/deleted line 

### ISSUE THREAD

**Issue by Hemachekuri** [NYCPlanning/labs-applicant-portal#181]
Chrome Browser
Actual:
Expected: Once the documents are uploaded, Document name is not  hyperlink and added with date is not displayed.
added document is not moved to below  the line as well and not giving an option for the user to delete.
Once the documents are uploaded, Document name should be hyperlink and added with date should be displayed.
added document shoud be moved to below  the line as well, giving an option for the user to delete.
User story: 10748 AC3 or 4
https://dcp-paperless.visualstudio.com/ZAP%20Portals/_workitems/edit/10532
Step: 17
![image](https://user-images.githubusercontent.com/63460627/81209517-a7244c00-8f9e-11ea-8a9a-a67ec9a726e3.png)

Expected: 
![image](https://user-images.githubusercontent.com/63460627/81210102-6416a880-8f9f-11ea-805d-839c84243d41.png)

**Comment by hannahkates** [comment]
@Hemachekuri The file name won't be provided as a hyperlink until the file has actually been saved to Dynamics CRM. In the screenshot you've shared, the file hasn't been saved yet, so it displays with black text.

I realize you can't save right now because of issue #187, so that makes it harder to see the full user journey for this. Let's keep this issue open to reevaluate once #187 is fixed.

**Comment by ksinghprod** [comment]
This issue is now fixed 
@Hemachekuri 

![image](https://user-images.githubusercontent.com/57362229/82257315-d5eadc80-9925-11ea-9a9c-91242ed1d41a.png)

![image](https://user-images.githubusercontent.com/57362229/82257397-f2871480-9925-11ea-96a6-e672f393711b.png)
