### ISSUE TITLE
Project area geography editor

### ISSUE THREAD

**Issue by hannahkates** [NYCPlanning/labs-applicant-portal#21]
## User Story
The applicant user needs to be able to view and edit their project's geography, indicating whether tax lots included are 1) partial or 2) a part of the development site.

## User Journey
- If a project already has BBLs saved to it, those BBLs should be listed (query MapPLUTO and display the address in parentheses next to the BBL string)
- If a project doesn't already has BBLs saved to it, a search input let's the user enter a BBL (or an address to see typeahead results) and a dropdown lets them add that BBL — as in ZoLa
- For each BBL, the user needs to indicate two yes/no attributes
  - Is the BBL part of the development site?
  - Is the BBL a partial lot?
- If the BBL they type in isn't valid, a visual indication is provided.
- The user can delete BBLs from the list. 

## Front End
**Functionality not shown in wireframes:**
- Search bar for typeahead (like in ZoLa search)
- For added BBLs, query MapPLUTO for the lot's address and display in parentheses next to the BBL string.
- For each BBL, the user needs to indicate two yes/no attributes 
  - Is the BBL part of the development site?
  - Is the BBL a partial lot?
- The user can only add BBLs that have been validated by GeoSearch.

### [Figma Wireframes](https://www.figma.com/file/aYB9O9Vpu31XvHubhLAusX/ZAP-Wireframes?node-id=0%3A1)

![image.png](https://images.zenhubusercontent.com/5ca23880d9fcf5278d71596e/42b63537-bd0f-4205-8b0a-a699f63f518f)

![image.png](https://images.zenhubusercontent.com/5ca23880d9fcf5278d71596e/2fa9f659-38a6-4c02-af29-c8cf2cb69bf6)

## Back End
- Each new BBL needs to be sent to CRM in the format that dcp_projectbbls entity expects. Borough, block, and lot need to be split out.
- This should also trigger the creation of the corresponding Project Address records.
- Writing the BBLs to the PAS form should trigger CRM's geography validation process. Our API should check for a response from that validation process.
![image.png](https://images.zenhubusercontent.com/5ca2425fd9fcf5278d7159e7/e2fe9951-0b01-4aa5-b045-a9444d5ca602)

## Unresolved Questions
- Writing the BBLs to the PAS form should trigger CRM's geography validation process. How can we get a response of whether the geography validation succeeds and provide any feedback to the user?

## Implementation Details
@allthesignals: I would start with creating a new component for this. In your test suite, you can run the component integration test. I would have it filtered to that integration test only. Then, develop your feature.

_Do_ make assumptions about the data structure. I think in this case it will be an array of BBLs. Use PLUTO from Carto to make the map.

**Comment by bean75** [comment]
ZAP is not set up to allow applicants to deactivate geo records (the PAS form does not currently give applicants that option). If you could figure that out it would be great, but not critical.

**Comment by andycochran** [comment]
> For each BBL, the user needs to indicate two yes/no attributes

This requirement makes me think that maybe a map and `<textarea>` isn't the right pair of UI elements. I had imagined that you could use either the map to toggle BBLs w/ a click OR paste comma-separated BBLs into the `<textarea>`, and changes to either one would update the other. 

If we need more UI for the list of BBLs, then each BBL will need its own discrete UI element for answering the two Qs about that BBL. 

This would mean keeping 3 UI components in sync: 
- Map
- `<textarea>`
- List of `<fieldset>` elements (containing 2 radios each) for each selected/listed BBL — similar to how applicant representatives and environmental consultants are added to the form

The BBL `<fieldset>` elements should be deletable — like how applicant representatives and environmental consultants can be deleted — and the map/`<textarea>` should be updated too. And if the BBL is removed from the map/`<textarea>` the corresponding `<fieldset>` element should be deleted. 

This seems complex but would allow for easily adding a long CSV of BBLs, and for searching the map with GeoSearch. 

#### Questions:
- Is there a way to simplify this UI so that it works for the majority of use cases, then iterate on a more comprehensive solution? 
- Can we assume a default answer for each BBL's 2 questions? 
- Is a partial lot always part of the development site? (Are there 3 or 4 states to the 2 questions?)

#### Idea:
Instead of simply toggling BBLs on/off, clicking a BBL on the map can cycle it through the various states — off, in project area, development site, partial lot, off… — and style them differently with a legend to indicate which is what. We could have a separate `<textarea>` element for each BBL state. Or we could format the `<textarea>` content so it's more than a simple comma-separated list of BBLs. It could include the answers to the questions inline: `4008760031, true, false, 4008760032, true, false...`

This feature is starting to feel bloated/overthought. I think we should have a quick design session to make sure the problem/user is clearly defined.

**Comment by bean75** [comment]
Development site question is more critical than partial lot question (partial lots are usually not the development site, usually they are stray bits in the rezoning boundary). I would assume no to both and just have them select yes as needed, if that helps?

**Comment by bean75** [comment]
Can we just have them either enter BBL from map or from text  - not both? Would that simplify?

**Comment by andycochran** [comment]
Yeah. Good idea, @bean75. I suppose the simplest UI would be a text input where BBLs are entered one at a time, and add a `<fieldset>` with the 2 Qs is added to the form for each BBL entered. The map/`<textarea>` could come later. The input could use GeoSearch — so it'd be predictive, allow for address or BBL, and have some simple validation before being sent to CRM.

**Comment by trbmcginnis** [comment]
@andycochran Trying to think about the benefits of using mappluto vs. geosearch to populate that address value that's displayed next to each bbl?

**If we use Geosearch**
1) First, we would use it in the backend to query addresses for each bbl that already exists in the db
2) We're already using it as the labs-search component in the frontend for users to search a bbl. When a user searches a bbl, the response is an object that has a `bbl` attribute and a `label` attribute which corresponds to the address. <-- we could use this `label` address value to populate the address property that we'll then send to the backend, meaning we won't have to query mappluto for a corresponding address. 

^^ This way we could avoid hitting the ZAP applicant portal API multiple times. Because we would only have to:

1) Hit geosearch once in the API to match addresses to bbls that already exist in the database
2) Hit geosearch once in the frontend each time a user searches a bbl, then send this to the backend once the user saves the PAS form

If we used mappluto we'd have to:

1) Hit mappluto in the API to match addresses to bbls that already exist in the database
2) Hit geosearch once in the frontend each time a user searches a bbl
3) Hit the API AGAIN to query mappluto to display the address corresponding to the new bbl just added by the user

Are we married to mappluto addresses for a reason? @allthesignals What do you think? I'm wondering if using geosearch is just less expensive
