### ISSUE TITLE
RWCDS Proposed Action(s) Section

### ISSUE THREAD

**Issue by nnxka** [NYCPlanning/labs-applicant-portal#223]
[Azure Requirement 10972](https://dcp-paperless.visualstudio.com/ZAP%20Portals/_workitems/edit/10972)
[AB#10972](https://dcp-paperless.visualstudio.com/d36fd830-9029-4b77-b0c4-b0df2012eb98/_workitems/edit/10972)
[AB#10974](https://dcp-paperless.visualstudio.com/d36fd830-9029-4b77-b0c4-b0df2012eb98/_workitems/edit/10974)

#### Zoning Actions subsection
1. The user sees a list of actions that they previously provided to NYC Planning listed in the form section for them
2. Depending on the type of zoning action, there are form inputs where the user needs to submit additional details
3. The user fills in missing details about the missing actions where it is necessary
4. If the user wants to add or delete zoning actions types, they have to contact DCP and follow the instructions

#### General Zoning Questions subsection
1. Depending on the users' zoning actions, some questions will be displayed
2. Regardless of the zoning actions, there are a few questions that are always asked

### [Wireframes](https://www.figma.com/file/aYB9O9Vpu31XvHubhLAusX/ZAP---Applicant-Portal?node-id=0%3A1)
![image.png](https://images.zenhubusercontent.com/5ca2425fd9fcf5278d7159e7/ea39475c-c72a-4155-91d9-5ce1ed5bbb9d)

#### "Zoning Action Type" subsection
  - Form should display all of the actions from the projects actions `dcp_projectaction`. Depending on the type of action, the form needs to show additional field inputs. Please refer to wireframe to see which actions have conditional questions. 
#### "Which actions from other agencies" question
  - If applicant answers TRUE for previous "Is applicant seeking action question", then show "which actions from other agencies" question and write to `dcp_whichactionsfromotheragenciesaresought`

#### General Zoning Questions subsection
There are 1 condition question and one piece of conditional text that gets displayed
1. Conditional text: Mandatory Inclusionary Housing (MIH)
2. Conditional question: Which actions from other agencies

### Attributes
  - [ ] `dcp_zoningresolution` (project action, entity = `dcp_projectaction` or 10127)
  - [ ] `dcp_zrmodifyingzrtxt` (project action, entity = `dcp_projectaction` or 10127)
  - [ ] `dcp_actiontype` (action, entity = `dcp_action` or 10094)

### Filter Logic
We only want records from `dcp_projectaction` where the status = active and the project id value is the same as the project whose package we are looking at

**Comment by trbmcginnis** [comment]
@hannahkates @nnxka I'm assuming `dcp_projecaction` entity has all the individual actions listed as rows.

Which entity are the fields that apply to all actions stored? (e.g. `dcp_purposeandneedfortheproposedactions`)

**Comment by trbmcginnis** [comment]
Looks like `dcp_isapplicantseekingactions` might have three options -- Yes, No, and Not Sure

@andycochran Should we update the wireframes or are we still only trying to have Yes & No as the two options?

https://dcppfsuat2.crm9.dynamics.com/api/data/v9.1/EntityDefinitions(LogicalName=%27dcp_rwcdsform%27)/Attributes(17e60dcd-ca9d-478c-addd-fbe03bb2c5ae)/Microsoft.Dynamics.CRM.PicklistAttributeMetadata?$select=LogicalName&$expand=OptionSet($select=Options),GlobalOptionSet($select=Options)

**Comment by hannahkates** [comment]
@trbmcginnis Good catch. Yes, we should add that, thanks

**Comment by trbmcginnis** [comment]
Okay so based on research into the CRM entities, here's how we're remapping the attributes from CRM to the frontend:

What we need in the frontend:
- dcpZoningresolutiontype (sourced from Entity: `dcp_projectaction` Attribute: `dcp_name`)
- dcpZrsectionnumber (sourced from Entity: `dcp_projectaction` Attribute: `dcp_zrsectionnumber)
- dcpZrsectiontitle (??)
- dcpModifiedzrsectionnumber (??)
- dcpIncludezoningtextamendment (??)

`dcp_name` (e.g. "ZA-Zoning Amendment") --> `dcpZoningresolutiontype` (e.g. "ZA")

**Comment by trbmcginnis** [comment]
**### Explanation of the problem**

We have been tasked with:

- Creating a component that lists out the actions associated with a project and allows users to edit one field that’s stored on the actions model `dcpModifiedzrsectionnumber`. All other editable fields included in the component are stored directly on the RWCDS form model.
- Copying data over from `dcp_projectaction` to `dcp_affectedzoningresolution`. We will be POSTing data that we GET from `dcp_projectaction` entity to `dcp_affectedzoningresolution` entity. 
The copying process from `dcp_projectaction` to `dcp_affectedzoningresolution` should look like this:

       - `dcp_name` (e.g. “ZA - Zoning Amendment) → `dcp_zoningresolutiontype` (“e.g. “ZA”)
       - `dcp_zrsectionnumber` → `dcp_zrsectionnumber`
       - `dcp_zrmodifyingzrtxt` → `dcp_modifiedzrsectionnumber`
       - Fill out various ID fields, explained below in the `Implementing the solution in our app`

- Our frontend will then just GET and PATCH to `dcp_affectedzoningresolution` directly

### **Case for a CRM enhancement instead of a labs-applicant-portal enhancement**

I don't think we should be handling this behavior at all in the app. I think this should be a CRM enhancement. I think it's not good code quality standards to have our API GET attributes from one database table just to automatically POST those same attributes to another database table. The remapping should happen automatically as an autofill in CRM. This feels outside the scope of our API, and therefore a "bandaid" on the problem rather than a solution at the root (in CRM) and I think this would result in problems and confusion in the long term. 

If these fields are autofilled in CRM, then the only thing we have to do is GET the attributes directly from dcp_affectedzoningresolution and then we can PATCH any attributes that the user inputs in our app.

### **Implementing the solution in our app**

These are the steps required to get the desired solution. They need to happen in a particular order:

1) `GET` `dcp_projectaction` with `dcp_project`

	Add this to the `expand` → `dcp_dcp_project_dcp_projectaction_project($filter=%20statuscode%20eq%201)`

2) Using a lifecycle hook, every time that we `GET` project actions we should `POST` what we get from `dcp_projectaction` to `dcp_affectedzoningresolution`. 
- In order to assure that we aren’t POSTing duplicates, we need to first check that the specific `dcp_affectedzoningresolutionid` does not already exist. Will we need to generate the value for this ID field ourselves? Not sure how this ID gets generated.
- We also need to make sure that we can join these rows to a specific RWCDS form for the future GETing of `dcp_affectedzonignresolution`. In order to do that we should check on the `dcp_rwcdsformid` that is associated with the current project’s package. Then when we POST to `dcp_affectedzoningresolution` we should make sure that this id is recorded in the field `_dcp_rwcdsform_value`.

3) `GET` dcp_affectedzoningresolution` associated with a specific `dcp_rwcdsform`

Add this to the `expand` → `dcp_rwcdsform_dcp_affectedzoningresolution_rwcdsform`

4) When a user updates the field `dcpModifiedzrsectionnumber` in the frontend and clicks the `Save` button, we `PATCH` to the associated `dcp_affectedzoningresolution`


**### dcp_projectaction actions vs. dcp_pasform actions**

We do have a `land-use-action` editor section on the PAS form. When users add actions on this component it PATCHes to the dcp_pasform entity. These actions are NOT usable for the purposes of displaying and editing on the RWCDS form. The actions on the PAS form are more like a rough first draft for actions associated with the project. It writes to `dcp_pasform` but it does NOT actually write to the actions for a project `dcp_projectaction`. Instead, planners create these actions in `dcp_projectaction` manually based on discussions with the applicant and what they entered into the PAS form. 

So using any info on the PAS form is not applicable here.

**Comment by hannahkates** [comment]
@trbmcginnis There was an update while you were on vacation. We do need to add the question asking for the section title. EARD does use the title number. Please see the updated wireframes on figma.
