### ISSUE TITLE
For the Proposed Land Use Actions field. when the user selects an change an option, the question and answer text box is displayed twice

### ISSUE THREAD

**Issue by Hemachekuri** [NYCPlanning/labs-applicant-portal#235]
## Browser(s) 
IE Browser and chrome

This issue is happening in all section,when user selects on another similar field is displayed.

## What should happen:
Proposed Land Use Actions, Proposed Land Use Actions. when the user selects Add a Proposed Action: change in city map, When user selects start entering character in input box, then another citymap should not be displayed,
## What happened instead:
Proposed Land Use Actions, Proposed Land Use Actions. when the user selects Add a Proposed Action: change in city map, When user selects start entering character in input box, then another citymap is displayed,
## How to reproduce this bug:
Log Into Applicant Portal
Click on the Edit Pre-Application Statement button
Navigate to the Proposed Land Use Actions, Proposed Land Use Actions. when the user selects Add a Proposed Action: change in city map, When user selects start entering character in input box, then another citymap is displayed,

Proposed Land Use Actions. when the user selects Add a Proposed Action: change in city map, 
![image](https://user-images.githubusercontent.com/63460627/81833494-ca567a80-950d-11ea-8d88-beffdde46830.png)
When user selects start entering character in input box, then another citymap is displayed,
![image](https://user-images.githubusercontent.com/63460627/81833595-e9eda300-950d-11ea-95aa-feec9a2f2e35.png)

**Comment by trbmcginnis** [comment]
okay I see what's going on, looks like the new filtering methods check for if an action already exists on the pasForm model and if it does, it adds it to an "existing" array. We're adding newly added actions to a "new" array and then combining the "new" and "existing" arrays. Because inputting a number in that input box causes a save directly to the model, the app is double counting that action and adding it to both the "new" and "existing" array -- meaning it's listed twice. Setting up a fix after the component meeting! and writing an associated test

**Comment by hannahkates** [comment]
@trbmcginnis I don't think it changes implementation for this bug, but want to link this issue with #245 for reference

**Comment by trbmcginnis** [comment]
@hannahkates Thanks! Going to implement this bug fix and then I'll tackle this one

**Comment by ksinghprod** [comment]
@hannahkates @Hemachekuri 
This issue is now fixed 

![image](https://user-images.githubusercontent.com/57362229/82091079-c0c34300-96c4-11ea-89a0-6aaa0116a691.png)
