### ISSUE TITLE
Revised Packages are not displaying the uploaded documents from previous version

### ISSUE THREAD

**Issue by ksinghprod** [NYCPlanning/labs-applicant-portal#311]
[AB#10532](https://dcp-paperless.visualstudio.com/d36fd830-9029-4b77-b0c4-b0df2012eb98/_workitems/edit/10532) 

## Browser(s) and Device(s) observed on:
Chrome, Firefox, IE
## What should happen:
Uploaded Documents from revision 1 of PAS form/package should carry over to the Version 2 PAS Package/form
## What happened instead:
Revised Packages, are not showing the uploaded documents from previous version

## How to reproduce this bug:

1. Log in to the Applicant Portal
2. Click on the Edit Pre-Application Statement Button
3. upload a document, save and submit
4. log into CRM, go to the same project, PAS form, create a revision loop (version 2 should be created)
5. log back into the Applicant Portal, click on the same Version 2 PAS form, navigate to the attached documents section (error can be seen here)

![image](https://user-images.githubusercontent.com/57362229/82357902-bf9b5a00-99d3-11ea-8efa-5be15430c9e6.png)

![image](https://user-images.githubusercontent.com/57362229/82358514-a1822980-99d4-11ea-8325-c557e03d532a.png)

![image](https://user-images.githubusercontent.com/57362229/82358574-b2329f80-99d4-11ea-826c-6521d7d59793.png)

**Comment by godfreyyeung** [comment]
When Bujji/Ella/Heidi called me, they were trying to debug this on the CRM side. Has that been fixed in CRM first?

**Comment by hannahkates** [comment]
Komal said the CRM issue was fixed a few hours ago.

**Comment by ksinghprod** [comment]
@hannahkates @godfreyyeung 

Here is the ADO Bug https://dcp-paperless.visualstudio.com/dcp-paperless-dynamics/_workitems/edit/10643

**Comment by godfreyyeung** [comment]
It appears the problem is that past revision documents are placed in a Sharepoint folder with a different naming schema than the traditional schema that Applicant Portal API assumes. Thus for a given Package revision, there are _two_ different Sharepoint folders to hold documents. One for past revision documents,  and one for files newly uploaded through the Applicant Portal. 

Applicant Portal API assumes this Sharepoint folder naming schema:
`<project> - <package name> - <revision>_<package id>`
(Where `<project> - <package name> - <revision>` is also the package name)
e.g. `2020K0398 - TestPackage1 - 14_C49EFC40E399EA11A811001DD8309D89`

Whereas past revision documents are placed in the folder:
`<project><package name><revision>_<package id>`
Notice there are no spaces or dashes between <project>, <package name> and <revision>
e.g. `2020K0398TestPackage114_C49EFC40-E399-EA11-A811-001DD8309D89`

**Comment by hannahkates** [comment]
@godfreyyeung Thank you for uncovering this!

@bean75 @ksinghprod @Eabrante Please see Godfrey's comment above. Is there a reason behind the different naming convention that is used for the folder containing the past revision documents? Also do you know if this folder naming convention is the same for all packages? We want to figure out if we should build a workaround for the inconsistent naming or if it's possible to rename the folders.

**Comment by godfreyyeung** [comment]
I've also pinged App Dev on teams: https://teams.microsoft.com/l/message/19:d1301588159a4ebcaf9c07d81ff59bd5

**Comment by bean75** [comment]
@hannahkates @godfreyyeung I think the interpretation is incorrect. The naming convention for the document folder is the full package name (there is a separate field for that - I wouldn't try to recreate it based on the component parts/fields)

**Comment by ksinghprod** [comment]
this issue is fixed 
cc @Hemachekuri 
![image](https://user-images.githubusercontent.com/57362229/85063299-ef2ab700-b177-11ea-83a5-981b92a10292.png)


![image](https://user-images.githubusercontent.com/57362229/85062889-4da36580-b177-11ea-82f4-264e7f738cdc.png)
