### ISSUE TITLE
Make sure all test selectors are consistent in format

### ISSUE THREAD

**Issue by godfreyyeung** [NYCPlanning/labs-applicant-portal#326]
Refactor data-test selectors to follow format of 

`data-test-[element type]="[property name]"`

For radio buttons:
`data-test-radio="[property name]"`
`data-test-radio-option="[property value]"`

![image.png](https://images.zenhubusercontent.com/5ced7833554ce77a5db49edf/9398f77d-827b-416b-8439-53e6ca623c70)

**Comment by trbmcginnis** [comment]
@godfreyyeung I'm writing validation tests now that include radio buttons. Just to double check that I'm using the correct conventions. For urban renewal area, are we going to use the `radio.label` (so "Yes")? (rather than the code e.g. `717170000`)

In the template:
`data-test-radio="dcpUrbanrenewalarea"`
`data-test-option="{{radio.label}}"`

In the test:
`[data-test-radio="dcpUrbanrenewalarea"] [data-test-option="Yes"]`
