### ISSUE TITLE
List addresses on the view-only PAS page

### ISSUE THREAD

**Issue by Hemachekuri** [NYCPlanning/labs-applicant-portal#339]
[AB#10532](https://dcp-paperless.visualstudio.com/d36fd830-9029-4b77-b0c4-b0df2012eb98/_workitems/edit/10532)
[AB#10747](https://dcp-paperless.visualstudio.com/d36fd830-9029-4b77-b0c4-b0df2012eb98/_workitems/edit/10747)

## What should happen:
View - Pre Application Statement .
In the Project Geography, address should displayed besides(BBL)
## What happened instead:
View - Pre Application Statement .
In the Project Geography, address in not displayed besides(BBL)
## Browser(s) and Device(s) observed on:
Log in to Applicant Portal
Click on the Edit-Pre Application Statement button
navigate to the Project Geography
Input the address in Add tax lots by searching for an address or BBL
save and submit,
now, click on View - Pre Application Statement .
In the Project Geography, address in not displayed besides(BBL)

![image](https://user-images.githubusercontent.com/63460627/82576805-20ec3600-9b58-11ea-9b69-b16b75aa8f87.png)

**Comment by hannahkates** [comment]
Because of the limitations of the data schema in CRM, it's not possible to connect the address with the BBL.

@bean75 should we list the addresses separately?

**Comment by bean75** [comment]
Yes, in the output they will show as two separate lists.

Sent from my iPhone

On May 21, 2020, at 4:43 PM, Hannah Kates <notifications@github.com> wrote:

﻿

Because of the limitations of the data schema in CRM, it's not possible to connect the address with the BBL.

@bean75<https://gcc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbean75&data=02%7C01%7Cafader%40planning.nyc.gov%7C38a1674ab29a489306a408d7fdc79718%7C32f56fc75f814e22a95b15da66513bef%7C0%7C0%7C637256905981899972&sdata=uFeJ9Dc4FsBNb9cxjC%2FbMqGFDqaX4lZ8uLgix8Nzv1M%3D&reserved=0> should we list the addresses separately?

**Comment by trbmcginnis** [comment]
@hannahkates @bean75 

A couple of questions before I jump on this:

Which field stores the project's addresses for the pas form? I'm seeing `dcp_developmentaddress`, `dcp_developmentsitegeographicaddresses`, `dcp_projectaddress`, and `dcp_addresses` as possible attributes on the PAS form. Or should I be looking in a different entity, maybe the project entity for a different address field?

Also do you know if these fields are pre-populated or will we have to do some sort of "lookup" using the bbls and mappluto/geosearch?

**Comment by hannahkates** [comment]
@trbmcginnis You should use the related dcp_projectaddress entity. It gets populated automatically when BBLs are created in the dcp_projectbbl entity.

**Comment by Hemachekuri** [comment]
working good. Closed
![image](https://user-images.githubusercontent.com/63460627/84941840-ea023500-b0af-11ea-9130-0221287316dc.png)

**Comment by godfreyyeung** [comment]
@ksinghprod  Can you send me the ID of the package displaying this error?

**Comment by hannahkates** [comment]
@godfreyyeung @ksinghprod The address is missing on the view-only PAS for [2020M0466](https://qa.applicant-portal.planninglabs.nyc/pas-form/3ff4e43f-f0ba-ea11-a812-001dd8309f0e). However, when I just looked in CRM, the address is actually blank for that record.
![image.png](https://images.zenhubusercontent.com/5ca2425fd9fcf5278d7159e7/4e5bbd68-cd2c-44ea-ab73-1b2fb2c44e81)

Addresses are showing up fine for [2020R0264](https://qa.applicant-portal.planninglabs.nyc/pas-form/c71881bd-5a23-ea11-a9ad-001dd8308025), so I think this is a data problem rather than a code bug.

**Comment by ksinghprod** [comment]
This issue is fixed as per Hannah's findings

![image](https://user-images.githubusercontent.com/57362229/87057651-1f90ce80-c1d5-11ea-9fa1-191f61bc193a.png)
