### ISSUE TITLE
PAS: Hitbox for deleting a file or "undo delete" is problematic

### ISSUE THREAD

**Issue by godfreyyeung** [NYCPlanning/labs-applicant-portal#444]
The hitbox for delete or "undo delete" is slightly below the actual X or undo symbol. When clicking X or undo symbol, the file doesn't switch between the delete and existing documents section as it should.

Currently you must click slightly under the X/undo button in order to actually trigger a delete or undo. 
![image.png](https://images.zenhubusercontent.com/5ced7833554ce77a5db49edf/0f54f45e-9a84-475c-a164-ecba39872de7)

![image.png](https://images.zenhubusercontent.com/5ced7833554ce77a5db49edf/de2c64e6-0441-40c7-aa83-1faa372b8bbe)

**Comment by godfreyyeung** [comment]
This also fixed by https://github.com/NYCPlanning/labs-applicant-portal/pull/451

**Comment by ksinghprod** [comment]
@hannahkates 

This issue is now fixed

![image](https://user-images.githubusercontent.com/57362229/86965441-9080a980-c135-11ea-9768-2550d1500806.png)

![image](https://user-images.githubusercontent.com/57362229/86965530-b8700d00-c135-11ea-87e8-2455d4a208d5.png)

![image](https://user-images.githubusercontent.com/57362229/86965612-d2115480-c135-11ea-8d75-9d915e57f745.png)
