### ISSUE TITLE
RWCDS packages are appearing on the applicant portal that do not have applicant only/general public visibility 

### ISSUE THREAD

**Issue by ksinghprod** [NYCPlanning/labs-applicant-portal#577]
## Browser:
Chrome,IE, Firefox
## Project:
Sprint N testing 

RWCDS packages are appearing on the applicant portal that do not have applicant only/general public visibility 

![image](https://user-images.githubusercontent.com/57362229/89058684-bad91780-d32d-11ea-9b18-b9185d86678d.png)

![image](https://user-images.githubusercontent.com/57362229/89058564-82393e00-d32d-11ea-8278-3b934dc558e2.png)

![image](https://user-images.githubusercontent.com/57362229/89058633-a268fd00-d32d-11ea-8fce-6ea7365524c2.png)

**Comment by nnxka** [comment]
Solution:
- Review backend logic

**Comment by trbmcginnis** [comment]
@ksinghprod Do you know if there is a way to manually update the Package Status Reason (`statuscode` field) on a package in CRM? I know that submitting the rwcds-form will update the package status reason to `Submitted` but I'm trying to manually update this field on a package to one of these values: `Mistake`/`Certified`/`Final Approval`/`Withdrawn`. This is for testing purposes, so that I can make sure projects with these statuses do NOT show up on the applicant portal.

**Comment by ksinghprod** [comment]
Hi Taylor, I replied to your comment in the ZAP channel 

You can click on the deactivate button (when the package is still active) on the package record and you will see a list of status reasons
