### ISSUE TITLE
Applicant is not able to see the project status of their project 

### ISSUE THREAD

**Issue by ksinghprod** [NYCPlanning/labs-applicant-portal#88]
Browser: Chrome 
Project ID: 2018M0365

Expected Result: Applicant should be able to see the following the details about their project on the landing pageL

Project Name (default sort)
Project ID
Project Status (Active or On-Hold)
Primary Applicant Name
Packages

Actual Result: User is unable to see the project status of their project 

![image](https://user-images.githubusercontent.com/57362229/79162001-763f6580-7daa-11ea-9b9c-7517e65840c9.png)

![image](https://user-images.githubusercontent.com/57362229/79161757-07faa300-7daa-11ea-883b-ac33d6990ee0.png)

**Comment by hannahkates** [comment]
@bean75 Thoughts on whether it's still beneficial to whether a project is "on hold"? This distinction hasn't come up in our recent convos about the wireframes. Since all projects in CRM are currently "on hold" we may want to hold off on implementing that since it could alarm users submitting PAS packages.

**Comment by bean75** [comment]
I think we should still proceed with it - and actually it is best that they see that everything is on pause.
________________________________

**Comment by ksinghprod** [comment]
This issue is now fixed 

![image](https://user-images.githubusercontent.com/57362229/79794649-9e861180-8320-11ea-88c8-dcd2d910f056.png)

**Comment by bfreeds** [comment]
Thank you @bean75 & @ksinghprod!
