### ISSUE TITLE
Upload a file to a PAS package

### ISSUE THREAD

**Issue by hannahkates** [NYCPlanning/labs-applicant-portal#9]
Here's a link to the existing Applicant Portal if it might help inform approaches: https://dcppfsuat2.dynamics365portals.us/applicants/overview/application-status-new/

**Comment by bfreeds** [comment]
Komal gave me a walkthrough yesterday of the Artifacts/Documents features in CRM and in the Microsoft Applicant Portal.  
# Artifacts 
> Artifacts are a data construct in CRM that represent documents.  There are two types of artifacts (project-related and package-related).    

### ZAP CRM  
#### Package Artifacts
1. View
![image](https://user-images.githubusercontent.com/5316367/75799831-a248df00-5d46-11ea-9c95-97cbea018540.png)
1. Edit
Click on existing Package's artifact
![image](https://user-images.githubusercontent.com/5316367/75810366-746c9600-5d58-11ea-9a99-8a05bc15aaca.png)
Planner can edit by changing values in these fields
![image](https://user-images.githubusercontent.com/5316367/75810427-90703780-5d58-11ea-8d32-7013cc003fbd.png)

1. Create 
  - Creating a "DCP Document", a document a planner would make
  - ![image](https://user-images.githubusercontent.com/5316367/75810890-72ef9d80-5d59-11ea-96fa-5c6231f8da0a.png)

1.  Delete
Clicking "Deactivate" in the menu bar gives this modal & options for deletion.  Will want to make sure our api query filters out for anything that's been deactivated.
![image](https://user-images.githubusercontent.com/5316367/75811996-708e4300-5d5b-11ea-8444-15c19cdc7309.png)

### Existing Applicant Portal
#### Package Artifacts 
1. View
1. Edit
![image](https://user-images.githubusercontent.com/5316367/75800604-d4a70c00-5d47-11ea-86c9-a405ee2f902b.png)  


The following fields are read-only:  
  - `Version`
  - `Project`
  - `Package`
  - `Package Type` and `File Creator` have dropdowns the user can click, but there aren't any options to select from.  
    - Are there other cases when there would be choose-able options here?
  - `Documents`
    - Can click add file, select file, and save.
    - This uploads to Sharepoint with the following URL:
    - https://nyco365.sharepoint.com/:i:/r/sites/dcppfsuat2/dcp_artifacts/2018K0354%20-%20Area%20Map%20-%201_1602F3BF4C20EA11A9AC001DD8308025/iu.jpeg?csf=1&e=Df4GNR
1. Create 
1.  Delete
### Labs Applicant Portal Wireframe
#### Package Artifacts

**Comment by allthesignals** [comment]
https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/get-to-know-the-sharepoint-rest-service?tabs=http

Great, @bfreeds — I don't think the /_services API is necessarily public? I'm not sure. I think this is the relevant feature:
https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/grids

I think what you're looking at are private APIs consumed by WYSIWYG features for Power BI or something. I don't think we would be able to use these endpoints...  this is just a guess...

The only endpoint I'm sure we can use is that sharepoint URL: https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/get-to-know-the-sharepoint-rest-service?tabs=http

**Comment by bfreeds** [comment]
@allthesignals that's right (`_services...`) is not public.  Looking at the Sharepoint REST API now.

The general process to upload a file will be to:
1. Upload file to the correct location in Sharepoint
  - `dcp_dcp_project_dcp_package_project`.`dcp_spabsoluteurl` field stores the absolute path to a project package location.  Need to find the 
1.  Update any impacted fields on the package artifact (need to identify exactly which fields we'll need to update).

**Comment by bfreeds** [comment]
Example response when expanding on `dcp_dcp_package_dcp_artifacts_package, an array of objects, each object being a package's artifacts.  

In this case, there are four objects because this is querying a PAS Package type.  When a Planner creates an "Action," depending on the type of action, CRM generates the necessary packages. 

For the file upload feature in Applicant Portal, these fields will help us understand how we have to configure the POST request to Sharepoint: 

```js
    "dcp_dcp_package_dcp_artifacts_package": [
        {
            "@odata.etag": "W/\"137742508\"",
            "dcp_filecategory": 717170000, // <== What's this?
            "_ownerid_value": "1abd727b-a759-ea11-a9ad-001dd8308022",
            "_createdonbehalfby_value": "1abd727b-a759-ea11-a9ad-001dd8308022",
            "versionnumber": 137742508, // auto-generated?
            "createdon": "2020-03-04T20:26:14Z",
            "_modifiedby_value": "01a8ad9a-38a9-e711-811e-1458d054d020",
            "_owningbusinessunit_value": "1ee911a6-c131-e811-812e-1458d04d95c0",
            "_dcp_projectactionid_value": null,
            "_dcp_project_value": "f330f0df-555e-ea11-a9b2-001dd8308025",
            "utcconversiontimezonecode": null,
            "dcp_oldartifactid": null,
            "_owninguser_value": "1abd727b-a759-ea11-a9ad-001dd8308022",
            "dcp_documentcomments": null,
            "_modifiedonbehalfby_value": null,
            "dcp_submittedfilename": "2020K0398_Official Zoning Sectional Map_3/4/2020 3:26 PM_ 1  ", // We'll need to submit this with the document creation / upload
            "_dcp_cpcmeeting_value": null,
            "dcp_dcpfilecategory": null,
            "modifiedon": "2020-03-05T22:41:23Z",
            "overriddencreatedon": null,
            "_dcp_applicantfiletype_value": "8d6fac7a-5edb-e711-8120-1458d04eb810",
            "_owningteam_value": null,
            "_dcp_package_value": "01023d5e-565e-ea11-a9b2-001dd8308025",
            "dcp_visibility": 717170002,
            "_createdby_value": "01a8ad9a-38a9-e711-811e-1458d054d020",
            "dcp_name": "2020K0398 - Official Zoning Sectional Map - 1", // *think* this is created for the applicant when the planner creates the "Action"
            "dcp_artifactsid": "c9923d64-565e-ea11-a9b2-001dd8308025", 
            "statuscode": 717170000,
            "statecode": 1, // ?
            "dcp_filecreator": 717170000,
            "dcp_version": 1, // part of the revision loop
            "dcp_publicstatus": null,
            "dcp_isrevisedartifact": false, // is this part of revision loop?  Would this be impacted if applicant edits/amends an uploaded artifact document?
            "importsequencenumber": null,
            "dcp_packagetype": 717170000,
            "_dcp_documentauthor_value": null,
            "dcp_isdcpinternal": false,
            "dcp_artifactdocumentlocation": "https://nyco365.sharepoint.com/sites/dcppfsuat2/dcp_artifacts/2020K0398 - Official Zoning Sectional Map - 1_C9923D64565EEA11A9B2001DD8308025", // NEEDS TO MATCH HOW WE UPLOAD THE ARTIFACT DOCUMENT
            "timezoneruleversionnumber": null,
            "dcp_documentdescription": null
        },
        {/* ...2nd artifact ...*/},
        {/* ...3rd package artifact... */},
        {/* ...4th package artifact... */}
    ]
```

**Comment by bfreeds** [comment]
@allthesignals after talking with @godfreyyeung today, I think the way we should approach this is to follow a similar pattern that is being used in `zap-api`.  Instead of directly using the Sharepoint Rest API for disposition uploads, my understanding is zap-api uploads dispositions through the crm api, rather than directly uploading files to Sharepoint.  [See here](https://github.com/NYCPlanning/labs-zap-api/blob/5854a5c8d65831d4ec3e38ff484f908ead2489b3/src/document/document.controller.ts#L63) for an example document upload.  

Here is where the CrmAPI interface defines the function to [uploadDocument](https://github.com/NYCPlanning/labs-zap-api/blob/5854a5c8d65831d4ec3e38ff484f908ead2489b3/src/_utils/crm-web-api.ts#L488).

That function contsructs the document location for a given entity, using fields that we can get from the Web API directly.  

For example, this file (which is an uploaded document on a project package artifact):
![image](https://user-images.githubusercontent.com/5316367/76451027-2df4e800-63a5-11ea-8a47-d83e4bcf810f.png)

Has an absolute filepath of:
`https://nyco365.sharepoint.com/sites/dcppfsuat2/dcp_artifacts/2020K0398 - Test Package Artifact - 1_839A96F0B363EA11A9A1001DD830812F`, which we have access to through `dcp_artifactdocumentlocation`.

**Next Steps**
- Confirm we can upload documents using the method in zap-api to the package artifact entity
- Confirm we can get document back using the same method
- Confirm that all the requisite fields on the entity record are updated (any autogenerated fields)

**Comment by allthesignals** [comment]
@bfreeds awesome awesome awesome. thank you.

**Comment by godfreyyeung** [comment]
### Retrieving a document investigation:

Can it be done through the CRM API?

Can we make a request directly to sharepoint?
